# Generated by Django 4.2.5 on 2023-09-17 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_expensecategory_historicalexpensecategory_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expensecategory',
            name='default_rate',
        ),
        migrations.RemoveField(
            model_name='historicalexpensecategory',
            name='default_rate',
        ),
    ]
