# Generated by Django 4.2.5 on 2023-10-04 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0004_vendor_remove_expense_merchant_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='cash',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalexpense',
            name='cash',
            field=models.BooleanField(default=False),
        ),
    ]
